In [1]:
#functions
#list
#dictionaries
import numpy as np

In [2]:
i=[1,2,3,4,5,6]

In [3]:
arr=np.array(i)

In [4]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

### pandas
- Import dataset
- Data cleaning
- Size mutability
- Reshaping and pivoting
- Efficient manipulation and extraction
- Statistical analysis

In [5]:

import pandas as pd
#primary data structures - series(1d), DataFreame(2d)

In [6]:
s = pd.Series([10,20,30,40,60])
s

0    10
1    20
2    30
3    40
4    60
dtype: int64

In [7]:
s.dtype

dtype('int64')

In [8]:
s.values

array([10, 20, 30, 40, 60])

In [9]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
s.name

In [11]:
s.name="calories"
s

0    10
1    20
2    30
3    40
4    60
Name: calories, dtype: int64

In [12]:
# Indexing
s[2:4]

2    30
3    40
Name: calories, dtype: int64

In [13]:
s.iloc[3]

np.int64(40)

In [14]:
s.loc[[0,3,4]]

0    10
3    40
4    60
Name: calories, dtype: int64

In [15]:
index=["apple", "banana","grapes","orange","dtrawberry"]

In [16]:
s.index=index
s

apple         10
banana        20
grapes        30
orange        40
dtrawberry    60
Name: calories, dtype: int64

In [17]:
s["grapes"]

np.int64(30)

In [18]:
s.iloc[3]

np.int64(40)

In [19]:
#loc -> label based indexing.
s.loc['grapes']

np.int64(30)

In [20]:
#In label based indexing your start as well as stop valu both are inclded
s['banana':'orange']

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

In [21]:
# using dictionaries
fruit_protein = {
    "guava": 2.0,
    "blackberries": 2.6,
    "oranges": 0.9,
    "banana": 1.1,
    "apples": 0.3,
    "kiwi": 1.1,
    "pomegranate": 1.7,
    "mango": 1.7,
    "cherries": 1.0
}

In [22]:
s2 = pd.Series(fruit_protein)
s2

guava           2.0
blackberries    2.6
oranges         0.9
banana          1.1
apples          0.3
kiwi            1.1
pomegranate     1.7
mango           1.7
cherries        1.0
dtype: float64

In [23]:
#Conditional seection
s2[s2>1]

guava           2.0
blackberries    2.6
banana          1.1
kiwi            1.1
pomegranate     1.7
mango           1.7
dtype: float64

In [24]:
#logical operators : and, or,, not
s2[(s2>0.5) & (s2<2)]

oranges        0.9
banana         1.1
kiwi           1.1
pomegranate    1.7
mango          1.7
cherries       1.0
dtype: float64

In [25]:
#modifying series
s2["mango"]=2.8
s2

guava           2.0
blackberries    2.6
oranges         0.9
banana          1.1
apples          0.3
kiwi            1.1
pomegranate     1.7
mango           2.8
cherries        1.0
dtype: float64

### DataFrame

In [78]:
data={
    "Name":["Alice","Bob","Charlie","David","Eve","Alice"],
    "Age":[25,30,35,np.nan,29,25],
    "Department":["HR","IT","Finance","IT","HR","HR"],
    "Salary":[50000,60000,70000,62000,np.nan,50000]
}

In [79]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [80]:
df=pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [81]:
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [82]:
df.tail(3)

    Name   Age Department   Salary
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [83]:
#loc & iloc
df.iloc[1:3]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [84]:

df.loc[1:3,["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [85]:
# accesing individual column
df[["Age","Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [86]:
# Dropping column
df.drop("Age",axis=1) # axis = 0 if we're dropping particular row

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [87]:
df.shape

(6, 4)

In [88]:
df.dtypes

Name              str
Age           float64
Department        str
Salary        float64
dtype: object

In [89]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Age         5 non-null      float64
 2   Department  6 non-null      str
 3   Salary      5 non-null      float64
dtypes: float64(2), str(2)
memory usage: 324.0 bytes

In [90]:
# Describe - gives ststistical information
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [91]:
# Broadcasting
df["Salary"]=df["Salary"]+5000
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [96]:
# Renaming columns
df.rename(columns={"Department": "Dept"},inplace=True)
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0

In [97]:
# checking for unique values
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

In [98]:
df["Dept"].unique()

<StringArray>
['HR', 'IT', 'Finance']
Length: 3, dtype: str

In [ ]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64