In [501]:
#functions
#list
#dictionaries
import numpy as np

In [502]:
i=[1,2,3,4,5,6]

In [503]:
arr=np.array(i)

In [504]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

### pandas
- Import dataset
- Data cleaning
- Size mutability
- Reshaping and pivoting
- Efficient manipulation and extraction
- Statistical analysis

In [505]:

import pandas as pd
#primary data structures - series(1d), DataFreame(2d)

In [506]:
s = pd.Series([10,20,30,40,60])
s

0    10
1    20
2    30
3    40
4    60
dtype: int64

In [507]:
s.dtype

dtype('int64')

In [508]:
s.values

array([10, 20, 30, 40, 60])

In [509]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [510]:
s.name

In [511]:
s.name="calories"
s

0    10
1    20
2    30
3    40
4    60
Name: calories, dtype: int64

In [512]:
# Indexing
s[2:4]

2    30
3    40
Name: calories, dtype: int64

In [513]:
s.iloc[3]

np.int64(40)

In [514]:
s.loc[[0,3,4]]

0    10
3    40
4    60
Name: calories, dtype: int64

In [515]:
index=["apple", "banana","grapes","orange","dtrawberry"]

In [516]:
s.index=index
s

apple         10
banana        20
grapes        30
orange        40
dtrawberry    60
Name: calories, dtype: int64

In [517]:
s["grapes"]

np.int64(30)

In [518]:
s.iloc[3]

np.int64(40)

In [519]:
#loc -> label based indexing.
s.loc['grapes']

np.int64(30)

In [520]:
#In label based indexing your start as well as stop valu both are inclded
s['banana':'orange']

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

In [521]:
# using dictionaries
fruit_protein = {
    "guava": 2.0,
    "blackberries": 2.6,
    "oranges": 0.9,
    "banana": 1.1,
    "apples": 0.3,
    "kiwi": 1.1,
    "pomegranate": 1.7,
    "mango": 1.7,
    "cherries": 1.0
}

In [522]:
s2 = pd.Series(fruit_protein)
s2

guava           2.0
blackberries    2.6
oranges         0.9
banana          1.1
apples          0.3
kiwi            1.1
pomegranate     1.7
mango           1.7
cherries        1.0
dtype: float64

In [523]:
#Conditional seection
s2[s2>1]

guava           2.0
blackberries    2.6
banana          1.1
kiwi            1.1
pomegranate     1.7
mango           1.7
dtype: float64

In [524]:
#logical operators : and, or,, not
s2[(s2>0.5) & (s2<2)]

oranges        0.9
banana         1.1
kiwi           1.1
pomegranate    1.7
mango          1.7
cherries       1.0
dtype: float64

In [525]:
#modifying series
s2["mango"]=2.8
s2

guava           2.0
blackberries    2.6
oranges         0.9
banana          1.1
apples          0.3
kiwi            1.1
pomegranate     1.7
mango           2.8
cherries        1.0
dtype: float64

### DataFrame

In [526]:
data={
    "Name":["Alice","Bob","Charlie","David","Eve","Alice"],
    "Age":[25,30,35,np.nan,29,25],
    "Department":["HR","IT","Finance","IT","HR","HR"],
    "Salary":[50000,60000,70000,62000,np.nan,50000]
}

In [527]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [528]:
df=pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [529]:
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [530]:
df.tail(3)

    Name   Age Department   Salary
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [531]:
#loc & iloc
df.iloc[1:3]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [532]:

df.loc[1:3,["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [533]:
# accesing individual column
df[["Age","Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [534]:
# Dropping column
df.drop("Age",axis=1) # axis = 0 if we're dropping particular row

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [535]:
df.shape

(6, 4)

In [536]:
df.dtypes

Name              str
Age           float64
Department        str
Salary        float64
dtype: object

In [537]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Age         5 non-null      float64
 2   Department  6 non-null      str
 3   Salary      5 non-null      float64
dtypes: float64(2), str(2)
memory usage: 324.0 bytes

In [538]:
# Describe - gives ststistical information
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [539]:
# Broadcasting
df["Salary"]=df["Salary"]+5000
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [540]:
# Renaming columns
df.rename(columns={"Department": "Dept"},inplace=True)
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0

In [541]:
# checking for unique values
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

In [542]:
df["Dept"].unique()

<StringArray>
['HR', 'IT', 'Finance']
Length: 3, dtype: str

In [543]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [544]:
# Creating new column
df["Promoted salary"]=df["Salary"]* 101
df

      Name   Age     Dept   Salary  Promoted salary
0    Alice  25.0       HR  55000.0        5555000.0
1      Bob  30.0       IT  65000.0        6565000.0
2  Charlie  35.0  Finance  75000.0        7575000.0
3    David   NaN       IT  67000.0        6767000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0        5555000.0

### Data cleaning

In [545]:
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted salary    1
dtype: int64

In [546]:
df.dropna() # na drops all rows with null values

      Name   Age     Dept   Salary  Promoted salary
0    Alice  25.0       HR  55000.0        5555000.0
1      Bob  30.0       IT  65000.0        6565000.0
2  Charlie  35.0  Finance  75000.0        7575000.0
5    Alice  25.0       HR  55000.0        5555000.0

In [547]:
df.dropna(how="any") # any row that had any null value

      Name   Age     Dept   Salary  Promoted salary
0    Alice  25.0       HR  55000.0        5555000.0
1      Bob  30.0       IT  65000.0        6565000.0
2  Charlie  35.0  Finance  75000.0        7575000.0
5    Alice  25.0       HR  55000.0        5555000.0

In [548]:
df.dropna(how="all") # if all values in a row are null otherwise will not be dropped

      Name   Age     Dept   Salary  Promoted salary
0    Alice  25.0       HR  55000.0        5555000.0
1      Bob  30.0       IT  65000.0        6565000.0
2  Charlie  35.0  Finance  75000.0        7575000.0
3    David   NaN       IT  67000.0        6767000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0        5555000.0

In [549]:
# Filling null values
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [550]:
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [551]:
# forward fill- top to bottom
df["Age"].bfill()

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [552]:
df["Name"]=df["Name"].replace("Charlie", "Rose")
df

    Name   Age     Dept   Salary  Promoted salary
0  Alice  25.0       HR  55000.0        5555000.0
1    Bob  30.0       IT  65000.0        6565000.0
2   Rose  35.0  Finance  75000.0        7575000.0
3  David   NaN       IT  67000.0        6767000.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  55000.0        5555000.0

In [553]:
# Dealing with duplicate values
df_dup=df[df.duplicated(keep="first")] # first occurrence is kept and rest are marked as duplicates
df_dup

    Name   Age Dept   Salary  Promoted salary
5  Alice  25.0   HR  55000.0        5555000.0

In [554]:
#Invalid values
df["Promoted salary"]=df["Promoted salary"].apply(lambda x: x/10 if x>65000 else x)
df

    Name   Age     Dept   Salary  Promoted salary
0  Alice  25.0       HR  55000.0         555500.0
1    Bob  30.0       IT  65000.0         656500.0
2   Rose  35.0  Finance  75000.0         757500.0
3  David   NaN       IT  67000.0         676700.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  55000.0         555500.0

In [555]:
#apply and lambda
def multiplying_age(x):
    return x*2
df["Age"]=df["Age"].apply(multiplying_age)
df

    Name   Age     Dept   Salary  Promoted salary
0  Alice  50.0       HR  55000.0         555500.0
1    Bob  60.0       IT  65000.0         656500.0
2   Rose  70.0  Finance  75000.0         757500.0
3  David   NaN       IT  67000.0         676700.0
4    Eve  58.0       HR      NaN              NaN
5  Alice  50.0       HR  55000.0         555500.0

In [556]:
df["Age"]=df['Age'].apply(lambda x:x/2)
df

    Name   Age     Dept   Salary  Promoted salary
0  Alice  25.0       HR  55000.0         555500.0
1    Bob  30.0       IT  65000.0         656500.0
2   Rose  35.0  Finance  75000.0         757500.0
3  David   NaN       IT  67000.0         676700.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  55000.0         555500.0

In [557]:
# Joins and merges
# left, right, inner, outer joins
department_info={
    "Department":["HR","IT","Finance"],
    "Location":["New York","San Francisco","Chicago"],
    "Manager":["John","Alice","Bob"]
}
df2=pd.DataFrame(department_info)
df2

  Department       Location Manager
0         HR       New York    John
1         IT  San Francisco   Alice
2    Finance        Chicago     Bob

In [558]:
# Concat
pd.concat([df,df2])

,Name,Age,Dept,Salary,Promoted salary,Department,Location,Manager
0,Alice,25.0,HR,55000.0,555500.0,NaN,NaN,NaN
1,Bob,30.0,IT,65000.0,656500.0,NaN,NaN,NaN
2,Rose,35.0,Finance,75000.0,757500.0,NaN,NaN,NaN
3,David,NaN,IT,67000.0,676700.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN
5,Alice,25.0,HR,55000.0,555500.0,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,HR,New York,John
1,NaN,NaN,NaN,NaN,NaN,IT,San Francisco,Alice
2,NaN,NaN,NaN,NaN,NaN,Finance,Chicago,Bob

In [560]:
pd.merge(df, df2, on="Dept")

KeyError: 'Dept'